### ISSUE TITLE
Integrate with the server

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#101]
We need to talk to the server. 

### TODO

- [x] Make the coordinates decimal
- [x] Fix the bug that nulls the position
- [x] Fix a bug that causes problems when assistance was added
- [x] no idea what but I bet there are more issues...
