### ISSUE TITLE
Localization of the App

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#40]
At the moment the CitizenApp is presented in english due to the international development team of the project. The end user will be german seniors.

### Task
- [x] Introduce a localization framework and document the choice
- [x] Discuss the choice with the team
- [x] Integrate the framework into the app
- [x] Create translation files for the german and english languages
- [x] Review of the approach

Responsible: @tim284 @patrickmuessig
Review: @skaldo, **done**

**Comment by skaldo** [comment]
I've edited the description a bit.

**Comment by tim284** [comment]
I think we already talked about ng2-translate, so the first two points should be clear. I made it work now and so i can start creating the translation files and integrates it into the whole app.

**Comment by skaldo** [comment]
@tim284 so as I understand it, you got it working and have some demo that already works. I'll have a look and do the review.

**Comment by tim284** [comment]
Exactly. It shows how to use it with a little example

**Comment by skaldo** [comment]
@tim284 everything looks fine. I've done some small changes in your code and introduced per-module lang.json files. I've summarised how this works in an wiki article: https://github.com/GSE-Project/SS2016-group2/wiki/I18N

After the translations of all hardcoded string in our app are done, we can merge this PR.

**Comment by tim284** [comment]
Gulpfile creates both language files (german, english) now, so the whole translation works.

**Comment by themetalone** [comment]
Reopened since not complete

- [ ] Stop-Detail Menue does not get translated
    - [ ] "Tasks"
    - [ ] "Show Bus information"
    - [ ] "Cancel"
- [ ] Stop-List: "Search"

**Comment by skaldo** [comment]
Just a note, the Stop-Detail translations you have to do in the `stop-detail.ts` file. Please use the synchronous `translateService.instant(param)` method to get the translations.

On the Stop-List page, please translate these two strings as well.
`<ion-refresher-content pullingText="Pull to refresh..." refreshingText="Refreshing...">`

Thanks!
