### ISSUE TITLE
CI: Host & update the application on gh-pages after each build

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#60]
#### TODO:
It would be nice to have to have the application uploaded to the GitHub pages after every single build on the Travis.

In order to achieve this following must be done:

- [ ] Rework the gh-pages #61 @skaldo

- [ ] Find the way how - use a bash script, or can Travis do this out-of-the-box? @themetalone 

- [ ] Update the .travis.yml @themetalone

**Comment by themetalone** [comment]
I trink this may be it 
https://gist.github.com/domenic/ec8b0fc8ab45f39403dd 
I'll Check compatibility

**Comment by skaldo** [comment]
Yes, I have found this one before too. We'll need to customize this a bit.

- [ ] Use our encrypted ssh keys
- [ ] Adjust the structure of gh-pages to something like:

/app - copied www directory
/docs - copied documentation
/index.html #61

I'll prepare then the new page with embedded view for our app as stated here #61.

**Comment by skaldo** [comment]
Closed due to the same reason as https://github.com/GSE-Project/SS2016-group2/issues/26#issuecomment-226954778.
