### ISSUE TITLE
Rework of GH Pages, introduce a new web presentation of this project

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#61]
#### TODO:

The current GH Page shows just the documentation. Every average project on the internet has a nice web presentation. As our project is awesome, a nice presentation is a must-have!

- [ ] Introduce a nice web presentation for our project

- [ ] Include the automatically generated application on this web presentation #60

- [ ] Embed the generated documentation on this web page #26

**Comment by themetalone** [comment]
Closed as the native map approach makes the webbuild impossible
