### ISSUE TITLE
Request Stops

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#63]
As stated in our requirements documentation the end user should be able to request a stop at the:
- current position (#SF_C11)

## Tasks

- [x] Clearify the design of the used interface with Group1 @GSE-Project/group1 @skaldo
- [x] Clearify the UI response to the user @GSE-Project/group2 
- [x] Implement UI
  - [x] Set address
  - [x] Set departure interval
  - [x] Set number of persons
  - [x] Add specialities (shopping assistance,...)
  - [x] Set name (as specified in the interface)
  - [x] Set Position (in this Iteration either the user points on the map **OR** the current device position)

- [x] Add interface to datalogic @themetalone

- [x] Implement [Request Interface](https://github.com/GSE-Project/SS2016-group2/wiki/Interface-meeting-RequestStops#json-interfaces) @themetalone
  - [x] POST
  - [x] GET
- [x] Handle the POST-Response (should contain `request_id` or something similiar @GSE-Project/group1 )
- [ ] Integrate into UI
  - [x] Add _make request_ page (to gather information for the request
  - [ ] Add notification about the state of the request
  - [ ] ? Add page with all open requests

**Comment by mbaniasad** [comment]
please contact me for discussion about the interface

**Comment by themetalone** [comment]
Set to Iteration 3 since the feature isn't yet implemented on the server

**Comment by skaldo** [comment]
I have prepared the 1st draft of the interface: https://github.com/GSE-Project/SS2016-group2/wiki/API-Proposal-for-SF_C4,-SF_C11---Request-(Custom)-Stop

@themetalone could you please have a look if I haven't missed anything?
@mbaniasad: This is the draft I mentioned in the e-mail, as I can't meet you tomorrow in person, please have a look. I would be happy to hear inputs from you too. Just let me know on Hangouts.

**Comment by mbaniasad** [comment]
1- id of device is a good Idea, but how is this going to be implemented? is there a special unique deviceid that can be sent or you should get the device Id from the server which would require the interface to be negotiated.

**Comment by themetalone** [comment]
I would recommend calling `window.device.uuid` or the cordova equivalent to get the ID at client side and pass it to the server.

**Comment by themetalone** [comment]
@mbaniasad  please have a look at [Interface proposal](https://github.com/GSE-Project/SS2016-group2/wiki/API-Proposal-for-SF_C4,-SF_C11---Request-(Custom)-Stop) since I reviewed some changes into it

**Comment by skaldo** [comment]
@themetalone This is the plugin we could use for the uuid: https://github.com/Paldom/UniqueDeviceID

**Comment by themetalone** [comment]
The Datalogic should now be able to request stops

**Comment by skaldo** [comment]
To keep it simple for this iteration I propose to do following:
- Do not provide address, name and assistance. As this is going to be almost always same for the requests done by particular device, we'd introduce a small "registration" page where the user would input the data. As all these informations are defined in the `ICitizenData`, I assume that these are sort of informational or optional (say, not required for successful placement of the request).
- At the beginning I'm going to implement request with following information:
 - Line
 - Number of persons
 - Location
 - Device id
- And a way how to show the accepted request(s) to the user.

I think this is the base functionality the customer requires for this iteration. During the 3rd iteration meeting, we can talk to the customer to refine the functionality.
