### ISSUE TITLE
Improvement of the transformation layer

### ISSUE THREAD

**Issue by skaldo** [GSE-Project/SS2016-group2#84]
I had a brief look at the new transformation layer. There can be some optimizations made. **These optimizations are going to reduce the complexity and and the maintenance effort.**

- [x] Introduce a constructor in all the viewModels as implemented in the ViewStop class. @themetalone
- [x] Then as we know the view type in the `getData` function, we can get rid of the `map: (data: D) => V` argument and in the function body do just just V(iRestModel). 
  - Replace the `map` parameter with a `constructorType` parameter

There might be an alternative for the steps 3 and 4, an introduction of an accessor method, that would provide us the data directly. `IRestStops.data(){return this.stops}`. _This would require us to have instances of the IRestObject. (I assume)_ If not, then it would be definitely a elegant solution.

These steps would help us to create more robust and easily understandable solution. **Another improvement** that could make it even nicer would be (requires medium-high effort):

- [ ] Implement a function on the CDS that would return the objects based on the type. Instead of `this.cds.getStops()` we would call `this.cds.get<IRestStops>()` or `this.cds.get(IRestStops)` 
(@themetalone: I don't think we need it anymore )

A side note, I don't think that we should deal with the IRestObjects at this level of our data access. I would say, that we should get only the plain data at this level, as we don't need the timestams. Try to rethink this @themetalone.

This issue is closely related to the #74.

@themetalone, you are assigned to this issue as you are the main developer of the data layer. Feel free to assign the other team members in order to help you.

-------
by @themetalone (160614) ( post it here since github considers mark boxes only in the first comment in an issue)

## TODO

- [x] Introduce constructor in the View objects and remove the then obsolete `Mapper`
- [x] Replace the `map` parameter with an `constructingType` parameter (needed since [We cannot use `new V()`](http://stackoverflow.com/questions/17382143/how-to-create-a-new-object-from-type-parameter-in-generic-class-in-typescript) )

- [x] Clean Up

**Comment by themetalone** [comment]
- Please consider that instanciating a generic type is not as simple as `new V()` as we saw in the early begining of our project. We would change the map paramter to a type. But true, this should be more elegant. 
- I wouldn't turn our interfaces into objects. We chose to have interfaces since it provides the flexibility we need when working with the rest interface. Implemented Methods aren't valid in tpescript interfaces. I think the approach with an data access field the most promising. Or we name it through all interfaces simply `data` but that would result in conflicts with the current rest api.

**Comment by skaldo** [comment]
Thanks @themetalone.

- That's definitely good point and I have missed it. See https://github.com/Microsoft/TypeScript/issues/2037 as an alternative to `c: {new(): T; }`. You can use it if you find it helpful.

- I agree with you on the dataAccess field. Anyway, you could investigate if it wouldn't be too much effort to make the CDS returning the `Array<T>` instead of the `IRestObject`. Afterwards this accessor would be used by the the CDS itself, and transformation layer would get the exposed data only.

- About the `data` property I thought at the beginning, but for some reason I did not find it good. I think, we can live without the change of the interface.

**Comment by themetalone** [comment]
I rewrote the CDS so we only return the `ICitizenDataObject[]` instead of the RestObjects

**Comment by themetalone** [comment]
Done and ready for Review. Change Log:

- Changed CDS return types to `Observable<D[]>` with `D extends ICitizenDataObject`
  - Adapted specs
- Reduced complexity of `TransformationLayer`
  - replaced `IRestObject` and `IRestAccess` parameters with `observableData:Observale<D[]>` 
  - replaced `map` parameter with `constructingType`
  - removed `map<D,V>` method since no longer needed
  - removed `Mapper`
  - adapted specs
- Adapted the View model
  - introduced `ViewObject` as common super type to the View model
  - added `constructor(d:T extends ICitzenDataObject)` to each View object
  - Added defaults for `ViewBus`

**Comment by themetalone** [comment]
And I marked all commits with #80 :(
