### ISSUE TITLE
Include Bus Seats

### ISSUE THREAD

**Issue by themetalone** [GSE-Project/SS2016-group2#85]
During the last testate the customer stated that we should be able to communicate the current number of free seats to the citizen.

### TODO

- [x] include property `totalSeats` to `IBus`
- [x] include property `takenSeats` to `IBusRealTimeData`
- [x] Add the delta to Bus-Detail-Page (#57 )

**Comment by tim284** [comment]
#85 The properties (total)seats and takenSeats are added, also in the correspondig ViewBus, View(Bus)RealtimeData. Can someone check Bus-Detail.ts if this would work?
